# Generated by Django 5.2.1 on 2025-10-14 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('triggers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trigger',
            name='coping_strategy',
            field=models.TextField(blank=True),
        ),
    ]
